Feature/improve readme
idrsolutions/jpedal-docker pull request #7
Opened 2021-08-18 11:31 UTC by KieranFrance

2021-08-18 14:10 UTC, markee174 approved these changes

2021-08-26 13:13 UTC, KieranFrance commented
I have made a couple more changes based on universal changes suggested in the related reviews

2021-08-31 15:52 UTC, leonatherton requested changes

2021-08-31 15:52 UTC, leonatherton commented on README.md
> +Once you have access, you can get and run the docker image with the following commands.
```suggestion
Once you have the JPedal war file, you can pull and run the docker image with the following commands:
```

2021-08-31 15:52 UTC, leonatherton commented on README.md
> +In order to use the JPedal Docker image you will need a license to access the JPedal war file. If you have not got a license yet, you can find our [free trial or contact us here](https://www.idrsolut
```suggestion
In order to use the JPedal Docker image you will need a license to access the JPedal war file. If you have not got a license yet, you can [sign up for a free trial](https://www.idrsolutions.com/jpedal/trial-download).
```

2021-08-31 15:52 UTC, leonatherton commented on README.md
> +[IDRSolutions JPedal Cloud Support Page](https://support.idrsolutions.com/jpedal/tutorials/cloud/).
```suggestion
[JPedal Cloud Documentation](https://support.idrsolutions.com/jpedal/tutorials/cloud/)
```

2021-08-31 15:52 UTC, leonatherton commented on README.md
> +[IDRSolutions JPedal Docker Support Page](https://support.idrsolutions.com/jpedal/tutorials/cloud/docker).
```suggestion
[JPedal Docker Documentation](https://support.idrsolutions.com/jpedal/tutorials/cloud/docker)
[Contact IDRsolutions](https://www.idrsolutions.com/contact-us)
```

2021-09-01 12:45 UTC, KieranFrance commented
The suggested changes have now been implemented

2021-09-01 15:39 UTC, leonatherton approved these changes

2021-09-09 08:15 UTC, merged